spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/apis/customers/** # Forward requests starting with /customers/
        - id: product-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/apis/products/**

server:
  port: 9000
  servlet:
    context-path: /apis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO
