spring.application.name=IP_Session_001
  
  # Use default naming strategy (Spring Boot 3 auto-converts to snake_case)

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.hibernate.ddl-auto=update

management.security.enabled=false

spring.datasource.url=jdbc:postgresql://dpg-d4an4h0gjchc73f08tj0-a.oregon-postgres.render.com:5432/render_postgres_ftlt?sslmode=require
spring.datasource.username=render_postgres_ftlt_user
spring.datasource.password=pj1o3qfqAFfdkMZ149D6xsLISVG4Ep6Y

spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
server.servlet.context-path=/apis
