project:
  app:
    jwtSecret: eW91cl9jbGllbnRfaWQ6eW91cl9jbGllbnRfc2VjcmV0
    jwtExpirationMs: 86400000

spring:
  application:
    name: auth-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # ============================
  # OAUTH2 CLIENT (Keycloak Login)
  # ============================
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: confidential-client
            client-secret: TqWB8Cnw0QGsjbdwEThe9DG6J1ljZTCG
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/auth-realm

      # ============================
      # RESOURCE SERVER (Validate JWT)
      # ============================
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/auth-realm


server:
  port: 8401
  servlet:
    context-path: /apis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    com.netflix.discovery: DEBUG
    com.example: INFO
    org.springframework: INFO
