spring:
  application:
    name: Order-Service

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # ----------------------------------------
  # RABBITMQ CONFIG
  # ----------------------------------------
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          max-attempts: 3

  # ----------------------------------------
  # KAFKA CONFIG
  # ----------------------------------------
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: generic-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*" # Trust all packages
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8083
  servlet:
    context-path: /apis

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      customerRetry:
        maxAttempts: 3
        waitDuration: 1s

  ratelimiter:
    instances:
      customerRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0
