spring.application.name=IP_Session_001

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Disable Spring Boot admin security
management.security.enabled=false

# --- Docker DB connection (important!) ---
spring.datasource.url=jdbc:postgresql://db:5432/ip_session_001
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# App config
server.port=8080
server.servlet.context-path=/apis
